apiVersion: v1
kind: Service
metadata:
  name: go-crud-app-service
spec:
  type: NodePort
  selector:
    app: go-crud-app
  ports:
  - name: go-crud-app
    port: 10000
    targetPort: 10000
  externalIPs:
    - 192.168.1.30
